# nixpacks.toml
[phases.setup]
# We build from source, so we need go + git. Caddy comes from Nix (no curl download).
nixPkgs = ["go", "git", "bash", "coreutils", "gnutar", "curl", "caddy"]

[phases.install]
cmds = [
  "set -e",
  "mkdir -p bin",

  # --- Choose the tag to build (defaults to v0.12.1). You can override GOPHISH_VER in Railway vars. ---
  "GOPHISH_VER=${GOPHISH_VER:-v0.12.1}",

  # --- Clone the tagged source and build a static-ish binary ---
  "rm -rf /tmp/gophish_src",
  "git clone --depth=1 --branch ${GOPHISH_VER} https://github.com/gophish/gophish /tmp/gophish_src",
  "cd /tmp/gophish_src && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /workspace/bin/gophish ./...",

  # --- Ensure VERSION file exists (strip leading 'v') next to the binary ---
  "echo ${GOPHISH_VER#v} > bin/VERSION",

  # --- Permissions ---
  "chmod +x bin/gophish"
]

[start]
# Run via shell to avoid executable-bit issues
cmd = "bash start.sh"
