# nixpacks.toml
[phases.setup]
# Keep it lean; no cacert. Add caddy from nix instead of downloading it.
nixPkgs = ["curl", "unzip", "gnutar", "coreutils", "bash", "caddy"]

[phases.install]
cmds = [
  "mkdir -p bin",
  # --- Gophish (download only this) ---
  "GOPHISH_VER=${GOPHISH_VER:-v0.12.1}; curl --proto '=https' --tlsv1.2 -fsSLo /tmp/gophish.zip https://github.com/gophish/gophish/releases/download/${GOPHISH_VER}/gophish-${GOPHISH_VER}-linux-64bit.zip",
  "unzip -o /tmp/gophish.zip -d bin",
  "chmod +x bin/gophish"
]

[start]
cmd = "bash start.sh"
